# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'present-rpc-example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for present-rpc-example
  pod 'SwiftProtobuf', '~> 1.0'

end
