// Code generated by present.rpc.JavascriptGenerator, do not edit.
// Source file: {{SourceFile}}

function {{ServiceName}}(url) {
  this.url = url;
}

{{ServiceName}}.prototype._post = function(path, arg) {
  var url = this.url + path;
  return new Promise(function (resolve, reject) {
    var xhr = new XMLHttpRequest();
    xhr.open("POST", url);
    xhr.onerror = function() {
      reject({
        request: xhr,
        code: xhr.status,
        message: xhr.statusText
      });
    }
    xhr.onload = function () {
      if (xhr.status >= 200 && xhr.status < 300) {
        resolve(xhr.response);
      } else {
        xhr.onerror();
      }
    };
    xhr.setRequestHeader("Content-Type", "application/json; charset=UTF-8");
    if (this.headers) {
      Object.keys(this.headers).forEach(function (key) {
        xhr.setRequestHeader(key, this.headers[key]);
      });
    }
    xhr.responseType = "json";
    xhr.send(JSON.stringify(arg));
  });
};
