// Code generated by present.rpc.JavascriptGenerator. DO NOT EDIT.
// Source file: {{fileName}}

import { present_rpc } from './present-rpc.mjs';

{{#services}}
export function {{serviceName}}(url, headers) {
  this.url = url ? url : "";
  this.headers = headers;
}

{{#rpcs}}
{{serviceName}}.prototype.{{rpcName}} = function(arg) {
  return present_rpc.post(this, '/{{serviceName}}/{{rpcName}}', arg);
};

{{/rpcs}}
{{/services}}
